spring.application.name=notification-service

server.port=8086

#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=w3softech45@gmail.com
spring.mail.password=dcmr axmq kvrf fxdn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

spring.mail.properties.mail.smtp.writetimeout=5000