spring.application.name=cart-service
spring.config.import=optional:configserver:http://localhost:8087

# Resilience4j Circuit Breaker configuration
#Enable health indicator
resilience4j.circuitbreaker.instances.productServiceCB.registerHealthIndicator=true
#Sliding window size
resilience4j.circuitbreaker.instances.productServiceCB.slidingWindowSize=10
#Failure rate threshold
resilience4j.circuitbreaker.instances.productServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productServiceCB.minimumNumberOfCalls=5
#Open state wait duration
resilience4j.circuitbreaker.instances.productServiceCB.waitDurationInOpenState=10000
#Half-open test calls
resilience4j.circuitbreaker.instances.productServiceCB.permittedNumberOfCallsInHalfOpenState=5
#Automatic transition 
resilience4j.circuitbreaker.instances.productServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true

#Actuator EndPoints
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,retries
management.endpoint.circuitbreakers.enabled=true
# Allow detailed actuator endpoints
management.endpoint.retries.enabled=true
# VERY IMPORTANT
management.endpoints.web.base-path=/actuator

#Retry
resilience4j.retry.instances.productServiceRetry.maxAttempts=3
resilience4j.retry.instances.productServiceRetry.waitDuration=1000

logging.level.io.github.resilience4j.retry=DEBUG

#RateLimiter
resilience4j.ratelimiter.instances.productServiceLimiter.limitForPeriod=2
resilience4j.ratelimiter.instances.productServiceLimiter.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.productServiceLimiter.timeoutDuration=0


